# Generated by Django 4.2.16 on 2026-06-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('validation_type', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI-Assisted')], default='manual', max_length=10)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('row_results', models.JSONField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='datasets.dataset')),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipeline_validation_runs',
                'ordering': ['-run_at'],
            },
        ),
    ]
