# Generated by Django 4.2.16 on 2026-06-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('record_ingested', 'Record Ingested'), ('batch_ingested', 'Batch Ingested'), ('validation_run', 'Validation Run'), ('record_promoted', 'Record Promoted'), ('dataset_created', 'Dataset Created'), ('dataset_published', 'Dataset Published'), ('dataset_archived', 'Dataset Archived'), ('version_created', 'Version Created'), ('record_corrected', 'Record Corrected'), ('taxonomy_updated', 'Taxonomy Updated'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('permission_changed', 'Permission Changed')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('layer', models.CharField(blank=True, max_length=10, null=True)),
                ('system', models.CharField(default='staff', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
