# Generated by Django 4.2.16 on 2026-06-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('license', models.CharField(default='CC BY 4.0', max_length=50)),
                ('access_tier', models.CharField(choices=[('public_free', 'Public Free'), ('researcher', 'Researcher'), ('api', 'API'), ('enterprise', 'Enterprise')], default='public_free', max_length=20)),
                ('version', models.CharField(default='0.1', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_datasets', to=settings.AUTH_USER_MODEL)),
                ('geographic_scope', models.ManyToManyField(blank=True, related_name='catalog_datasets', to='taxonomy.geographynode')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_catalog_datasets', to=settings.AUTH_USER_MODEL)),
                ('records', models.ManyToManyField(blank=True, related_name='catalog_appearances', to='datasets.dataset')),
                ('sector_scope', models.ManyToManyField(blank=True, related_name='catalog_datasets', to='taxonomy.sectornode')),
            ],
            options={
                'db_table': 'catalog_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_versions', to=settings.AUTH_USER_MODEL)),
                ('published_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='catalog.publisheddataset')),
            ],
            options={
                'db_table': 'catalog_dataset_versions',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
